version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=restaurant
      # - MONGO_INITDB_USERNAME=root
      # - MONGO_INITDB_PASSWORD=111111
    volumes:
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo/db:/data/db

volumes:
  mongo:
    driver: local
networks:
  mongo:
    driver: bridge
